; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Sun Nov 04 2018 19:45:48 GMT-0800 (Pacific Standard Time)
; Wait for set temperatures to be reached
M116 P0